<?php

namespace Database\Seeders;

use App\Models\Dimensions;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DimensionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$dimensions = array(
    		array('request_type_id' => 1, 'label' => '4.25 x 6.87 inches (Mass market paperback )'),
    		array('request_type_id' => 1, 'label' => '5.5 x 8.5 inches (Trade Paperbacks)'),
    		array('request_type_id' => 1, 'label' => '6 x 9 inches (Hardcover Books)'),
    		array('request_type_id' => 1, 'label' => '4.25 x 6.87 inches (Fiction Books)'),
    		array('request_type_id' => 1, 'label' => '5 x 8 inches (Novellas)'),
    		array('request_type_id' => 1, 'label' => '7 x 10 inches (Children\'s Book)'),
    		array('request_type_id' => 1, 'label' => '8.5 x 11 inches (Textbooks)'),
    		array('request_type_id' => 1, 'label' => '20.8 x 33.3 inches (General)'),
    		array('request_type_id' => 1, 'label' => '22.2 x 35.6 inches (Kindle)'),
    		array('request_type_id' => 1, 'label' => '7.1 x 11.1 inches (Wattpad)'),
    		array('request_type_id' => 1, 'label' => '14.9 x 20.1 inches (Kobo)'),
    		array('request_type_id' => 2, 'label' => '21 x 29.7 cm'),
    		array('request_type_id' => 4, 'label' => '600 px width (Standard)'),
    		array('request_type_id' => 4, 'label' => '640 px width (Alternative)'),
    		array('request_type_id' => 5, 'label' => '300 x 250 px (Medium Banner)'),
    		array('request_type_id' => 5, 'label' => '728 x 90 px (Leader Board)'),
    		array('request_type_id' => 5, 'label' => '160 x 600 px (Wide Skyscraper)'),
    		array('request_type_id' => 5, 'label' => '300 x 600 px (Halfpage)'),
    		array('request_type_id' => 5, 'label' => '970 x 90 px (Large Leaderboard)'),
    		array('request_type_id' => 5, 'label' => '970 x 250 px (Billboard)'),
    		array('request_type_id' => 5, 'label' => '120 x 600 px (Skyscraper)'),
    		array('request_type_id' => 5, 'label' => '200 x 200 px (Small Square)'),
    		array('request_type_id' => 5, 'label' => '250 x 250 px (Square)'),
    		array('request_type_id' => 5, 'label' => '120 x 240 px (Vetical Banner)'),
    		array('request_type_id' => 5, 'label' => '468 x 60 px (Full Banner)'),
    		array('request_type_id' => 5, 'label' => '234 x 60 px (Half Banner)'),
    		array('request_type_id' => 6, 'label' => '8.27 x 5.83inches'),
    		array('request_type_id' => 7, 'label' => '9,449 x 23,622 px (Banner)'),
    		array('request_type_id' => 7, 'label' => '14,043 x 9,933 px (A0)'),
    		array('request_type_id' => 7, 'label' => '9,933 x 7,016 px (A1)'),
    		array('request_type_id' => 7, 'label' => '7,016 x 4,961 px (A2)'),
    		array('request_type_id' => 7, 'label' => '4,961 x 3,508 px (A3)'),
    		array('request_type_id' => 7, 'label' => '3,508 x 2,480 px (A4)'),
    		array('request_type_id' => 7, 'label' => '2,480 x 1748 px (A5)'),
    		array('request_type_id' => 7, 'label' => '1,748 x 1,240 px (A6)'),
    		array('request_type_id' => 7, 'label' => '1,240 x 874 px (A7)'),
    		array('request_type_id' => 8, 'label' => '8.27 x 11.69 inches (A4)'),
    		array('request_type_id' => 8, 'label' => '11x 8.5 inches (Letter)'),
    		array('request_type_id' => 8, 'label' => '8.5 x 14 inches (Legal)'),
    		array('request_type_id' => 8, 'label' => '8.5 x 5.5 inches (Half Letter)'),
    		array('request_type_id' => 8, 'label' => '11 x 17 inches (Tabloid)'),
    		array('request_type_id' => 9, 'label' => '180 x 180 px (Profile Picture)'),
    		array('request_type_id' => 9, 'label' => '820 x 312 px (Cover Photo)'),
    		array('request_type_id' => 9, 'label' => '1,200 x 630 px (Image Post)'),
    		array('request_type_id' => 9, 'label' => '1,200 x 628 px (Shared Link Images)'),
    		array('request_type_id' => 9, 'label' => '111 x 74 px (Tab Images)'),
    		array('request_type_id' => 9, 'label' => '1,200 x 1,080 px (Event Image)'),
    		array('request_type_id' => 9, 'label' => '1,200 x 628 px (Facebook Ads)'),
    		array('request_type_id' => 9, 'label' => '1,080 x 1,920 px (Stories)'),
    		array('request_type_id' => 9, 'label' => '1,080 x 1,080 px (Square Images)'),
    		array('request_type_id' => 9, 'label' => '110 x 110 px (Profile Photo)'),
    		array('request_type_id' => 9, 'label' => '1,080 x 1,080 px (Square Images)'),
    		array('request_type_id' => 9, 'label' => '1,080 x 1,350 px (Images)'),
    		array('request_type_id' => 9, 'label' => '1,080 x 1,920 px (Stories)'),
    		array('request_type_id' => 9, 'label' => '800 x 800 px (Channel Icon)'),
    		array('request_type_id' => 9, 'label' => '2,560 x 1,440 px (Channel Art)'),
    		array('request_type_id' => 9, 'label' => '2,560 x 423 px (Desktop Display)'),
    		array('request_type_id' => 9, 'label' => '1,855 x 423 px (Tablet Display)'),
    		array('request_type_id' => 9, 'label' => '1,546 x 423 px (Desktop and Mobile Display)'),
    		array('request_type_id' => 9, 'label' => '1,280 x 720 px (Video Thumbnail)'),
    		array('request_type_id' => 9, 'label' => '1,500 x 500 px (Header Photo)'),
    		array('request_type_id' => 9, 'label' => '400 x 400 px (Profile Photo)'),
    		array('request_type_id' => 9, 'label' => '1,024 x 512 px (Twitter Post)'),
    		array('request_type_id' => 9, 'label' => '800 x 320 px (Cards Image)'),
    		array('request_type_id' => 9, 'label' => '280 x 150 px (Summary Card Image)'),
    		array('request_type_id' => 9, 'label' => '400 x 400 px (Profile Photo)'),
    		array('request_type_id' => 9, 'label' => '1,584 x 396 px (Cover Photo)'),
    		array('request_type_id' => 9, 'label' => '180 x 110 px (Shared Image)'),
    		array('request_type_id' => 9, 'label' => '1,200 x 628 px (Linked Post)'),
    		array('request_type_id' => 9, 'label' => '1,200 x 1,200 px (Image Post)'),
    		array('request_type_id' => 10, 'label' => '3.54 x 1.97 inches'),
    		array('request_type_id' => 10, 'label' => '3.54 x 2.17 inches'),
    		array('request_type_id' => 10, 'label' => '3.35 x 2.17 inches'),
    		array('request_type_id' => 10, 'label' => '3.5 x 2 inches'),
    		array('request_type_id' => 10, 'label' => '3.54 x 2.13 inches'),
    		array('request_type_id' => 10, 'label' => '3.43 x 2.24 inches'),
    		array('request_type_id' => 10, 'label' => '3.35 x 1.89 inches'),
    		array('request_type_id' => 10, 'label' => '3.58 x 2.17 inches'),
    		array('request_type_id' => 11, 'label' => '500 x 500 px (Image)'),
    		array('request_type_id' => 12, 'label' => '5.5 x 8.5 inches (Half Sheet)'),
    		array('request_type_id' => 12, 'label' => '8.5 x 11 inches (Standard)'),
    		array('request_type_id' => 12, 'label' => '11 x 17 inches (Large Format)'),
    		array('request_type_id' => 13, 'label' => '2.5 x 3.5 inches (2R)'),
    		array('request_type_id' => 13, 'label' => '3.5 x 5 inches (3R)'),
    		array('request_type_id' => 13, 'label' => '4 x 6 inches (4R)'),
    		array('request_type_id' => 13, 'label' => '5 x 7 inches (5R)'),
    		array('request_type_id' => 13, 'label' => '6 x 8 inches (6R)'),
    		array('request_type_id' => 13, 'label' => '8 x 10 inches (8R)'),
    		array('request_type_id' => 13, 'label' => '8 x 12 inches (S8R)'),
    		array('request_type_id' => 13, 'label' => '10 x 12 inches (10R)'),
    		array('request_type_id' => 14, 'label' => '16 x 16 px'),
    		array('request_type_id' => 14, 'label' => '24 x 24 px'),
    		array('request_type_id' => 14, 'label' => '32 x 32 px'),
    		array('request_type_id' => 14, 'label' => '48 x 48 px'),
    		array('request_type_id' => 14, 'label' => '64 x 64 px'),
    		array('request_type_id' => 14, 'label' => '156 x 156 px'),
    		array('request_type_id' => 14, 'label' => '256 x 256 px'),
    		array('request_type_id' => 15, 'label' => '500 x 500 px'),
    		array('request_type_id' => 15, 'label' => '1080 x 1080 px'),
    		array('request_type_id' => 15, 'label' => '1500 x 1500 px'),
    		array('request_type_id' => 16, 'label' => '8 x 5 inches (Junior Legal)'),
    		array('request_type_id' => 16, 'label' => '8.5 x 11 inches (Letter)'),
    		array('request_type_id' => 16, 'label' => '8.5 x 14 inches (Legal)'),
    		array('request_type_id' => 16, 'label' => '11 x 17 inches (Tabloid)'),
    		array('request_type_id' => 17, 'label' => '1920 x 1080 px'),
    		array('request_type_id' => 17, 'label' => '1024 x 768 px'),
    		array('request_type_id' => 18, 'label' => '3,000 x 3,000 px'),
    		array('request_type_id' => 18, 'label' => '1,400 x 1,400 px'),
    		array('request_type_id' => 19, 'label' => '1,200 x 628 px (Featured Images)'),
    		array('request_type_id' => 19, 'label' => '500 x 500 px (Author Image)'),
    		array('request_type_id' => 19, 'label' => '1,200 x 628 px (Facebook Preview Image)'),
    		array('request_type_id' => 19, 'label' => '1,024 x 512 px (Twitter Post Preview)'),
    		array('request_type_id' => 19, 'label' => '150 x 150 px (Thumbnail Image)'),
    		array('request_type_id' => 19, 'label' => '600 x 1,280 px (Screenshots)'),
    		array('request_type_id' => 20, 'label' => '11 x 11 inches (Standard Adult)'),
    		array('request_type_id' => 20, 'label' => '11.25 x 14 inches (Maximum Adult)'),
    		array('request_type_id' => 20, 'label' => '14 x 11.25 inches (Super Maximum Adult)'),
    		array('request_type_id' => 20, 'label' => '10.5 x 10.5 inches (Youth Med - Large)'),
    		array('request_type_id' => 20, 'label' => '8.5 x 8.5 inches (Youth Small)'),
    		array('request_type_id' => 20, 'label' => '5.5 x 5.5 inches (Toddler)'),
    		array('request_type_id' => 21, 'label' => '3.5 x 4 inches (Wine Label)'),
    		array('request_type_id' => 21, 'label' => '4 x 3 inches (Beer Label)'),
    		array('request_type_id' => 21, 'label' => '8 x 2 inches (Water Bottle Label)'),
    		array('request_type_id' => 21, 'label' => '2.63 x 1 inch (Address Tag)'),
    		array('request_type_id' => 21, 'label' => '3.38 x 2.31 inches (Name Tag)'),
    		array('request_type_id' => 21, 'label' => '4 x 6 inches (International Shipping Label)'),
    		array('request_type_id' => 22, 'label' => '14 x 48 feet'),
    		array('request_type_id' => 22, 'label' => '10 x 40 feet'),
    		array('request_type_id' => 22, 'label' => '10.5 x 36 feet'),
    		array('request_type_id' => 23, 'label' => '8 x 5 inches (Junior Legal)'),
    		array('request_type_id' => 23, 'label' => '8.5 x 11 inches (Letter)'),
    		array('request_type_id' => 23, 'label' => '8.5 x 14 inches (Legal)'),
    		array('request_type_id' => 23, 'label' => '11 x 17 inches (Tabloid)'),
    		array('request_type_id' => 24, 'label' => '1920 x 1080 px')
    	);

        // Create Dimensions
    	foreach($dimensions as $dimension){
            Dimensions::create($dimension);
        }
    }
}
